Oop
TheHomelessHacker/SberTech pull request #2
Opened 2024-03-18 18:48 UTC by TheHomelessHacker

Opp, почему-то все-равно лишние файлы закинулись

2024-03-18 18:50 UTC, TheHomelessHacker commented
И ещё последнее задание как-то не очень получилось

2024-03-27 17:41 UTC, XLelarX requested changes

2024-03-27 17:41 UTC, XLelarX commented on OOP/src/main/java/Book/Book.java
> +    public static void main(String[] args) {
Лучше сделать один Main класс и в там один main метод, который будет вызывать private-методы, тестирующие функционал

2024-03-27 17:41 UTC, XLelarX commented on OOP/src/main/java/Book/Book.java
> +class Book {
Такие классы надо сделать public, и оставить только его в файле

2024-03-27 17:41 UTC, XLelarX commented on OOP/src/main/java/Book/Book.java
> +    protected Author(String name, String sex, String email){
Конструктор должен быть public + находиться сразу же после полей в классе

2024-03-27 17:41 UTC, XLelarX commented on OOP/src/main/java/Book/Book.java
> +    public static void main(String[] args) {
ненужный main-метод

2024-03-27 17:41 UTC, XLelarX commented on OOP/src/main/java/Circle/Circle.java
> +    private static final double Pi = 3.1415926535;
Не надо создавать такую константу, тем более что есть Math.PI

2024-03-27 17:41 UTC, XLelarX commented on OOP/src/main/java/Matrix/Matrix.java
> +//        matrix1.setValue(0, 0, 1);
Ненужные комменты

2024-03-27 17:41 UTC, XLelarX commented on OOP/src/main/java/Matrix/Matrix.java
> +        sum.PrintMatrix();
название методов должно быть с маленькой буквы

2024-03-27 17:41 UTC, XLelarX commented on OOP/src/main/java/Matrix/Matrix.java
> +    protected Matrix SumMatrix(Matrix other){
Методы с маленьких букв пишутся

2024-03-27 17:41 UTC, XLelarX commented on OOP/src/main/java/Paint/Point.java
> +        /*
ненужный коммент

2024-03-27 17:41 UTC, XLelarX commented on OOP/src/main/java/Paint/Point.java
> +abstract class Figure {
В одном файле должен находиться только один класс

2024-03-27 17:41 UTC, XLelarX commented on OOP/src/main/java/Paint/Point.java
> +    double width;
Поля в таких классах должны быть private

2024-03-27 17:41 UTC, XLelarX commented on OOP/src/main/java/Phone/Phone.java
> +        //System.out.println("Звонит " + name + " , номер " + number_phone);
коммент

2024-03-27 17:41 UTC, XLelarX commented on OOP/src/main/java/Phone/Phone.java
> +    protected static void receiveCall(String name, String number_phone){
названия переменных не должно содержать _

2024-03-27 17:41 UTC, XLelarX commented on OOP/src/main/java/PizzaOrder/PizzaOrder.java
> +        switch (size) {
switch выглядит бесполезным, так как можно задать поле String description у enum-а и использовать его

2024-03-27 17:41 UTC, XLelarX commented on base/src/main/java/Home_Work.java
> +        for (int i = 1; i < n; i++)
названия переменных должны быть более осмысленными

2024-03-27 17:41 UTC, XLelarX commented on .idea/.gitignore
папка .idea должна быть добавлена в .gitignore

2024-03-27 17:41 UTC, XLelarX commented on OOP/src/main/java/Book/Book.java
> +    private String BookName;
Названия переменных начинаются с буквы в нижнем регистре

2024-03-27 17:41 UTC, XLelarX commented on OOP/src/main/java/PizzaOrder/PizzaOrder.java
> +        PizzaOrder pizza = new PizzaOrder("Сырная", PizzaSize.BIG, true, "Пушкинская 6");
Параметры типа "Сырная", "Пушкинская 6" и тд лучше заносить в костанты

2024-03-27 17:41 UTC, XLelarX commented on base/src/main/java/Home_Work.java
> +        //System.out.println(Arrays.toString(numbers));
коммент

2024-03-27 17:41 UTC, XLelarX commented on base/src/main/java/Home_Work.java
> +                //System.out.println(n + " ");
коммент

2024-03-27 17:41 UTC, XLelarX commented on OOP/src/main/java/PizzaOrder/PizzaOrder.java
> +    public void cansel() {
canсel)

2024-04-18 20:13 UTC, XLelarX approved these changes

2024-06-03 19:53 UTC, merged